name: Testing and validation

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8, 11, 14 ]
        env: [ development ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Set up Chrome driver
      uses: nanasess/setup-chromedriver@master
    - name: Run all tests
      run: mvn clean verify -P${{ matrix.env }} -Dspring.profiles.active=test
